#!/bin/bash

brew install wget

# Development tools
brew install vim
brew install zsh
brew install iterm2

brew install python3

brew install git

brew install caskroom/cask/brew-cask

# software
brew cask install google-chrome
brew cask install firefox
brew cask install spotify

# cleanup
brew cask cleanup

