#!/bin/bash

brew install wget

# Development tools
brew install vim
brew install zsh
brew install zsh-completions

brew install python3

brew install git

brew install caskroom/cask/brew-cask

# software
brew cask install google-chrome
brew cask install firefox
brew cask install spotify
brew cask install iterm2
brew cask install dropbox
brew cask install 1password
brew cask install sublime-text

# cleanup
brew cleanup

